controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    left_hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

    right_hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

ocs2_arm_controller:
  ros__parameters:
    update_rate: 100
    info_file_name: task  # 确保文件名指向正确的 Task.info
    robot_name: arx_lift2s
    
    # 必须精确包含 13 个受控关节
    joints:
      - lift_joint
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6

    command_interfaces:
      - position
    state_interfaces:
      - position

    # 数组长度必须为 13
    home_pos: [0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    rest_pos: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]